/**
 * Bundles webview-src/ into a single string constant that the React Native side
 * inlines into the WebView's HTML.
 *
 * The WebView cannot resolve bare module specifiers or fetch files from the app
 * bundle, so the editor has to arrive pre-bundled. Committing the generated
 * file means `npm start` works without running this script first; rerun it with
 * `npm run build:webview` after touching anything under webview-src/.
 */
import { build } from 'esbuild';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = path.join(root, 'src', 'webview', 'bundle.generated.ts');

const result = await build({
  entryPoints: [path.join(root, 'webview-src', 'index.ts')],
  bundle: true,
  write: false,
  format: 'iife',
  platform: 'browser',
  target: ['es2019'],
  minify: true,
  legalComments: 'none',
  // Stylesheets are imported as raw text so the bundle can inject them itself,
  // and the editor font arrives as a data URL, so the editor font works offline
  // with no asset plumbing. Both keep the WebView shell free of build-time
  // dependencies.
  loader: { '.css': 'text', '.ttf': 'dataurl' },
  logLevel: 'warning',
});

const [output] = result.outputFiles;
if (!output) {
  throw new Error('esbuild produced no output');
}

const code = output.text;
const byteLength = Buffer.byteLength(code, 'utf8');

// U+2028 and U+2029 are legal in modern string literals but break older
// parsers, and esbuild leaves them alone. Escaping them keeps the generated
// module loadable by every JavaScript engine the app might run on.
const escaped = code
  .replace(/\u2028/g, '\\u2028')
  .replace(/\u2029/g, '\\u2029');

const header = `/* eslint-disable */
// GENERATED FILE — do not edit by hand.
// Source: webview-src/  ·  Generated by: npm run build:webview
`;

const body = `export const WEBVIEW_BUNDLE = ${JSON.stringify(escaped)};

/** Size of the bundle in bytes, useful when watching it for regressions. */
export const WEBVIEW_BUNDLE_BYTES = ${byteLength};
`;

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, header + body, 'utf8');

console.log(
  `webview bundle: ${(byteLength / 1024).toFixed(1)} KiB -> ${path.relative(
    root,
    outputPath,
  )}`,
);
